### ISSUE TITLE
Add conversion of coordinates to allow Scraper control

### ISSUE THREAD

**Issue by aguinanc** [lnls-dig/basler-acA1300-75gm-epics-ioc#1]
It should be possible to use the same IOC to control both Slits (linear motion) and Scrapers (angular to linear motion). This should require new records or a different .db.

The following equation for the Scraper motion has been defined:
protuberance = r_big*sinD(ang_zero+rot_angle)-r_small
r_big = 99 mm
r_small = 40 mm
ang_zero = asinD(r_small/r_big) = 23.831 deg

**Comment by lerwys** [comment]
This functionality would be better suited for lnls-dig/diff-ctrl-epics-ioc repository, it seems.

**Comment by aguinanc** [comment]
Moved to lnls-dig/diff-ctrl-epics-ioc#1
